<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/pandas/pandas_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas kutubxonasi-DataFrame malumotlar tuzilmasi.

In [2]:
import pandas as pd

In [3]:
data = {
    "Yil": [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    "Aholi soni": [33.9, 33.1, 32.5, 31.9, 31, 31.2,29.8,28.7],
    "temp": [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
}

In [4]:
data

{'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
 'Aholi soni': [33.9, 33.1, 32.5, 31.9, 31, 31.2, 29.8, 28.7],
 'temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]}

In [9]:
df1 = pd.DataFrame(data) # data lug'atimizdan df1 nomli dataframe yaratildi.

In [6]:
df1

    Yil  Aholi soni  temp
0  2021        33.9  1.54
1  2020        33.1  1.48
2  2019        32.5  1.56
3  2018        31.9  1.62
4  2017        31.0  1.65
5  2016        31.2  1.66
6  2015        29.8  1.64
7  2010        28.7  1.53

In [ ]:
df1.head() # head metodi default qiymatida 5 ta elementni qaytaradi.

    Yil  Aholi soni  temp
0  2021        33.9  1.54
1  2020        33.1  1.48
2  2019        32.5  1.56
3  2018        31.9  1.62
4  2017        31.0  1.65

In [ ]:
df1.head(6)

    Yil  Aholi soni  temp
0  2021        33.9  1.54
1  2020        33.1  1.48
2  2019        32.5  1.56
3  2018        31.9  1.62
4  2017        31.0  1.65
5  2016        31.2  1.66

In [ ]:
df1.shape

(8, 3)

In [ ]:
df1 = pd.DataFrame(data, columns=['Yil', 'temp', 'Aholi soni']) # columnlar ketma ketligini o'zimiz belgiladik.

In [ ]:
df1.head()

    Yil  temp  Aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.1
2  2019  1.56        32.5
3  2018  1.62        31.9
4  2017  1.65        31.0

In [ ]:
df1 = pd.DataFrame(data, columns=['Yil', 'temp', 'Aholi soni'], index=[15,16,17,18,19,20,21,22]) # indexlarni o'zimiz belgiladik.

In [ ]:
df1.head()

     Yil  temp  Aholi soni
15  2021  1.54        33.9
16  2020  1.48        33.1
17  2019  1.56        32.5
18  2018  1.62        31.9
19  2017  1.65        31.0

In [7]:
df1 = pd.DataFrame(data, columns=['Yil', 'temp', 'Aholi soni','YaIM',"o'rtacha yosh"]) # bu yerdan qo'shimcha bo'sh bo'lgan ustunlar kiritdik.

In [8]:
df1.head()

    Yil  temp  Aholi soni YaIM o'rtacha yosh
0  2021  1.54        33.9  NaN           NaN
1  2020  1.48        33.1  NaN           NaN
2  2019  1.56        32.5  NaN           NaN
3  2018  1.62        31.9  NaN           NaN
4  2017  1.65        31.0  NaN           NaN

In [ ]:
df1['Aholi soni'].head()

0    33.9
1    33.1
2    32.5
3    31.9
4    31.0
Name: Aholi soni, dtype: float64

In [ ]:
df1.Yil.head() # bu usul har doim ham ishlamaydi.

0    2021
1    2020
2    2019
3    2018
4    2017
Name: Yil, dtype: int64

In [ ]:
type(df1.Yil) # ko'rishimiz mumkin bu Series malumotlar tuzilmasidan iborat.

pandas.core.series.Series

In [ ]:
df1.YaIM = 0

In [ ]:
df1

    Yil  temp  Aholi soni  YaIM o'rtacha yosh
0  2021  1.54        33.9     0           NaN
1  2020  1.48        33.1     0           NaN
2  2019  1.56        32.5     0           NaN
3  2018  1.62        31.9     0           NaN
4  2017  1.65        31.0     0           NaN
5  2016  1.66        31.2     0           NaN
6  2015  1.64        29.8     0           NaN
7  2010  1.53        28.7     0           NaN

In [ ]:
tempor = pd.Series([3100,3000,2500],index=[0,1,4]) # o'zimiz hoxlagan joyga hoxlagan malumotimizni kiritdik.

In [ ]:
df1.YaIM = tempor

In [ ]:
df1

    Yil  temp  Aholi soni    YaIM o'rtacha yosh
0  2021  1.54        33.9  3100.0           NaN
1  2020  1.48        33.1  3000.0           NaN
2  2019  1.56        32.5     NaN           NaN
3  2018  1.62        31.9     NaN           NaN
4  2017  1.65        31.0  2500.0           NaN
5  2016  1.66        31.2     NaN           NaN
6  2015  1.64        29.8     NaN           NaN
7  2010  1.53        28.7     NaN           NaN

In [ ]:
tempor = pd.Series([3100,3000,2910,2825,2700,2550,2410,2250])

In [ ]:
df1.YaIM = tempor

In [ ]:
df1

    Yil  temp  Aholi soni  YaIM o'rtacha yosh
0  2021  1.54        33.9  3100           NaN
1  2020  1.48        33.1  3000           NaN
2  2019  1.56        32.5  2910           NaN
3  2018  1.62        31.9  2825           NaN
4  2017  1.65        31.0  2700           NaN
5  2016  1.66        31.2  2550           NaN
6  2015  1.64        29.8  2410           NaN
7  2010  1.53        28.7  2250           NaN

In [ ]:
df1['yangi_level'] = df1.YaIM > 2700

In [ ]:
df1

    Yil  temp  Aholi soni  YaIM o'rtacha yosh  yangi_level
0  2021  1.54        33.9  3100           NaN         True
1  2020  1.48        33.1  3000           NaN         True
2  2019  1.56        32.5  2910           NaN         True
3  2018  1.62        31.9  2825           NaN         True
4  2017  1.65        31.0  2700           NaN        False
5  2016  1.66        31.2  2550           NaN        False
6  2015  1.64        29.8  2410           NaN        False
7  2010  1.53        28.7  2250           NaN        False

In [ ]:
del df1["o'rtacha yosh"]

In [ ]:
df1

    Yil  temp  Aholi soni  YaIM  yangi_level
0  2021  1.54        33.9  3100         True
1  2020  1.48        33.1  3000         True
2  2019  1.56        32.5  2910         True
3  2018  1.62        31.9  2825         True
4  2017  1.65        31.0  2700        False
5  2016  1.66        31.2  2550        False
6  2015  1.64        29.8  2410        False
7  2010  1.53        28.7  2250        False

In [ ]:
data = {
    'Uzbekistan':{2026:38.5,2025:37.6,2024:36.9,2023:35.5,2022:34.8,2021:33.6,2020:32.7},
    'Kazakhstan':{2026:18.5,2025:17.6,2024:16.9,2023:15.5,2022:14.8,2021:13.6,2020:12.7,2018:12},
}

In [ ]:
df2 = pd.DataFrame(data) # bu yerda indexlari ham kiritilgan dataframe yaratib oldik.
df2

      Uzbekistan  Kazakhstan
2026        38.5        18.5
2025        37.6        17.6
2024        36.9        16.9
2023        35.5        15.5
2022        34.8        14.8
2021        33.6        13.6
2020        32.7        12.7
2018         NaN        12.0

In [ ]:
df2.index.name = 'yil' # indexga nom berdik.
df2

      Uzbekistan  Kazakhstan
yil
2026        38.5        18.5
2025        37.6        17.6
2024        36.9        16.9
2023        35.5        15.5
2022        34.8        14.8
2021        33.6        13.6
2020        32.7        12.7
2018         NaN        12.0

In [ ]:
df3 = pd.DataFrame(data, index=[2026,2024,2018]) # o'zimiz hoxlagan indexdagi malumotlarni kiritib dataframe yaratdik.
df3

      Uzbekistan  Kazakhstan
2026        38.5        18.5
2024        36.9        16.9
2018         NaN        12.0

In [ ]:
df2.index.name = 'yil'

In [ ]:
df2.T # column va qatorlar o'rnini almashtirdik.

yil         2026  2025  2024  2023  2022  2021  2020  2018
Uzbekistan  38.5  37.6  36.9  35.5  34.8  33.6  32.7   NaN
Kazakhstan  18.5  17.6  16.9  15.5  14.8  13.6  12.7  12.0

In [ ]:
df2.values # malumotlarni array ko'rinishiga o'tgazdik.

array([[38.5, 18.5],
       [37.6, 17.6],
       [36.9, 16.9],
       [35.5, 15.5],
       [34.8, 14.8],
       [33.6, 13.6],
       [32.7, 12.7],
       [ nan, 12. ]])

In [ ]:
type(df2.values)

numpy.ndarray

In [ ]:
df1

    Yil  temp  Aholi soni YaIM o'rtacha yosh
0  2021  1.54        33.9  NaN           NaN
1  2020  1.48        33.1  NaN           NaN
2  2019  1.56        32.5  NaN           NaN
3  2018  1.62        31.9  NaN           NaN
4  2017  1.65        31.0  NaN           NaN
5  2016  1.66        31.2  NaN           NaN
6  2015  1.64        29.8  NaN           NaN
7  2010  1.53        28.7  NaN           NaN

## Indexlar bilan ishlash.

In [ ]:
indexs = df1.columns # bu yerda indexlar bilan ishlash uchun alohida o'zgaruvchiga saqlab oldik.
indexs

Index(['Yil', 'temp', 'Aholi soni', 'YaIM', 'o'rtacha yosh'], dtype='object')

In [ ]:
indexs[2:4]

Index(['Aholi soni', 'YaIM'], dtype='object')

In [ ]:
'YaIM' in indexs # bazi columnlarimiz bor yoki yo'qligini tekshirdik.

True

In [ ]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}
df3 = pd.DataFrame(data)

In [ ]:
df3

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com

In [ ]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}

In [ ]:
df4 = pd.concat([df3,pd.DataFrame(data2)]) # bu yerda 2 ta dataframeni bir biriga qo'shib alohida dataframe yaratdik.

In [ ]:
df4

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
df4.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
newind1 = pd.Index(['olim','nafisa','hamida']) # yangi indeks yaratdik.
newind1

Index(['olim', 'nafisa', 'hamida'], dtype='object')

### indexning bazi method va parametrlarini ko'ramiz

In [ ]:
newind1.isin(df4.index) # newind1 elementlari df4 indexlari ichida bor yo'qligini tekshirdik.

array([ True, False, False])

In [ ]:
df4.index.difference(newind1) # df4 va newind1 indexlarni bir biriga solishtirdik ularning farqini ko'rdik.

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [ ]:
newind1.difference(df4.index) # newind1 va df4 indexlarni bir biriga solishtirdik ularning farqini ko'rdik.

Index(['hamida', 'nafisa'], dtype='object')

In [ ]:
df4.index.union(newind1) # bu yerda ikki indexlarni bir biriga qo'shdik. takrorlangan elementlarning hech biri yo'qolmaydi.

Index(['anvar', 'hamida', 'javohir', 'maryam', 'maryam', 'nafisa', 'olim',
       'olim'],
      dtype='object')

In [ ]:
df4.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
df4.index.delete(1) # bu yerda 1 ta indexni o'chirib tashladik.

Index(['anvar', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
df4

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
newind1

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [ ]:
newind1.drop('nafisa') # bu yerda bir indexni olib tashladik. bu yerda indexlarning indexsi bilan murojat qila olmaymiz.

Index(['olim', 'hamida'], dtype='object')

In [ ]:
newind1.insert(1,'sancho') # hohlagan joyimizga yangi index qo'shdik.

Index(['olim', 'sancho', 'nafisa', 'hamida'], dtype='object')

In [ ]:
df4.index.is_monotonic_increasing # o'suvchi yoki kamayuvchiligini tekshiradi.

False

In [ ]:
df4.index.is_unique # indexlar unique yoki yo'qligini tekshiradi.

False

In [ ]:
newind1.is_unique

True

In [ ]:
df4.index.unique() # elementlarni unique qilib qaytaradi. yani bir xil elementlarni faqat 1 marta qaytaradi.

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

## Qayta indexlash

In [10]:
df1

    Yil  Aholi soni  temp
0  2021        33.9  1.54
1  2020        33.1  1.48
2  2019        32.5  1.56
3  2018        31.9  1.62
4  2017        31.0  1.65
5  2016        31.2  1.66
6  2015        29.8  1.64
7  2010        28.7  1.53

In [11]:
# indexlarni o'zgartirish.
df1.index=[21,20,19,18,17,16,15,10]

In [12]:
df1

     Yil  Aholi soni  temp
21  2021        33.9  1.54
20  2020        33.1  1.48
19  2019        32.5  1.56
18  2018        31.9  1.62
17  2017        31.0  1.65
16  2016        31.2  1.66
15  2015        29.8  1.64
10  2010        28.7  1.53

In [14]:
# reindex.
ind = [21,20,19,18,17,16,15,10] # bu yerda sorting qilingan indexni kiritdik.
ind.sort()
df1.reindex(index = ind)

     Yil  Aholi soni  temp
10  2010        28.7  1.53
15  2015        29.8  1.64
16  2016        31.2  1.66
17  2017        31.0  1.65
18  2018        31.9  1.62
19  2019        32.5  1.56
20  2020        33.1  1.48
21  2021        33.9  1.54

In [15]:
df1 # hali bizning asl malumotlarimiz o'zgargani yo'q.

     Yil  Aholi soni  temp
21  2021        33.9  1.54
20  2020        33.1  1.48
19  2019        32.5  1.56
18  2018        31.9  1.62
17  2017        31.0  1.65
16  2016        31.2  1.66
15  2015        29.8  1.64
10  2010        28.7  1.53

In [16]:
df1.reindex(index=[21,19,16]) # o'zimiz hoxlagan indexdagi malumotlarni oldik.

     Yil  Aholi soni  temp
21  2021        33.9  1.54
19  2019        32.5  1.56
16  2016        31.2  1.66

In [19]:
df1.reindex(index = range(10,22), method='ffill')

     Yil  Aholi soni  temp
10  2010        28.7  1.53
11  2015        29.8  1.64
12  2015        29.8  1.64
13  2015        29.8  1.64
14  2015        29.8  1.64
15  2015        29.8  1.64
16  2016        31.2  1.66
17  2017        31.0  1.65
18  2018        31.9  1.62
19  2019        32.5  1.56
20  2020        33.1  1.48
21  2021        33.9  1.54

In [22]:
df1.reindex(columns=['Aholi soni','temp']).sample(5) # o'zimiz hoxlagan columnlarni chiqardik.

    Aholi soni  temp
15        29.8  1.64
19        32.5  1.56
21        33.9  1.54
16        31.2  1.66
20        33.1  1.48

In [24]:
# loc methodi.
df1.loc[[15,18,20],['Yil',"Aholi soni"]] # o'zimiz hoxlagan index va ustunlarni ajratib oldik.

     Yil  Aholi soni
15  2015        29.8
18  2018        31.9
20  2020        33.1

In [25]:
df1

     Yil  Aholi soni  temp
21  2021        33.9  1.54
20  2020        33.1  1.48
19  2019        32.5  1.56
18  2018        31.9  1.62
17  2017        31.0  1.65
16  2016        31.2  1.66
15  2015        29.8  1.64
10  2010        28.7  1.53

In [26]:
# drop methodi.
df1.drop([20,18,17,10]) # o'zimiz hoxlagan qatorlarni tashlab yubordik.

     Yil  Aholi soni  temp
21  2021        33.9  1.54
19  2019        32.5  1.56
16  2016        31.2  1.66
15  2015        29.8  1.64

In [27]:
df1.drop(['Yil','temp'], axis =1)# bazi ustunlarni tashlab yubordik. lekin haliasl malumotimizga o'zgarish kiritmadik.

    Aholi soni
21        33.9
20        33.1
19        32.5
18        31.9
17        31.0
16        31.2
15        29.8
10        28.7

In [28]:
df1

     Yil  Aholi soni  temp
21  2021        33.9  1.54
20  2020        33.1  1.48
19  2019        32.5  1.56
18  2018        31.9  1.62
17  2017        31.0  1.65
16  2016        31.2  1.66
15  2015        29.8  1.64
10  2010        28.7  1.53

In [29]:
df1.drop(10,inplace=True)# bu yerda asl malumotlarimizga joyida o'zgartirish kiritdik inplace ni qo'llab.

In [30]:
df1

     Yil  Aholi soni  temp
21  2021        33.9  1.54
20  2020        33.1  1.48
19  2019        32.5  1.56
18  2018        31.9  1.62
17  2017        31.0  1.65
16  2016        31.2  1.66
15  2015        29.8  1.64