<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/pandas/pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas kutubxonasi bilan tanishamiz.

## Series malumotlar tuzilmasi.

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series

In [ ]:
series1 = Series([3,7,4,9,1]) # bu yerda pandas kutubxonasining Series malumotlar tuzilmasidagi object yaratib oldik.
print(series1)

0    3
1    7
2    4
3    9
4    1
dtype: int64

In [ ]:
type(series1)

pandas.core.series.Series

In [ ]:
series1.values # obyektning faqat qiymatlarini ko'rishimiz mumkin.

array([3, 7, 4, 9, 1])

In [ ]:
series1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
series1[1:4]

1    7
2    4
3    9
dtype: int64

In [ ]:
series2 = Series([9,3,-5,12,-7], index=["a",'b','c','d','e']) # Seriesning pythondagi malumot turlaridan asosiy farqi bunda biz indexlarni o'zimiz kiritishimiz mumkin.

In [ ]:
print(series2)

a     9
b     3
c    -5
d    12
e    -7
dtype: int64

In [ ]:
series2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
series2[['e','c','b']]

e   -7
c   -5
b    3
dtype: int64

In [ ]:
series2[series2>1]

a     9
b     3
d    12
dtype: int64

In [ ]:
series2*10

a     90
b     30
c    -50
d    120
e    -70
dtype: int64

In [ ]:
np.sqrt(series2)

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

a    3.000000
b    1.732051
c         NaN
d    3.464102
e         NaN
dtype: float64

## Lugatlar va Serieslar bilan ishlash.

In [ ]:
cars_dic = {'spark':6000,"cobalt":14000,"gentra":15000,'tracker':22000,"onix":20000}

In [ ]:
cars_series = Series(cars_dic) # bu yerda lugatni seriesga aylantirib oldik.
print(cars_series)

spark       6000
cobalt     14000
gentra     15000
tracker    22000
onix       20000
dtype: int64

In [ ]:
'cobalt' in cars_series

True

In [ ]:
'malibu' in cars_series

False

In [ ]:
cars_series['tracker']

np.int64(22000)

In [ ]:
model = ['cobalt','onix','BMW','tracker','spark','gentra','mersedes']

In [ ]:
cars2_series = Series(cars_dic, index = model) # bu yerda biz o'zimiz hoxlagan tartibdagi indexli abyekt yaratib oldik.

In [ ]:
cars2_series

cobalt      14000.0
onix        20000.0
BMW             NaN
tracker     22000.0
spark        6000.0
gentra      15000.0
mersedes        NaN
dtype: float64

## series metodlari va parametrlari.

In [ ]:
cars2_series.isnull() # bu metod bizda bo'sh elementlarni true holatda qaytaradi.

cobalt      False
onix        False
BMW          True
tracker     False
spark       False
gentra      False
mersedes     True
dtype: bool

In [ ]:
cars2_series.notnull() #bu metod mavjuda bo'lmagan elementlarni false holatda qaytaradi.

cobalt       True
onix         True
BMW         False
tracker      True
spark        True
gentra       True
mersedes    False
dtype: bool

In [ ]:
cars2_series + cars_series # series ustida qo'shish amamlini bajarsak indexlari mos elementlarning qiymatlari qo'shiladi.

BMW             NaN
cobalt      28000.0
gentra      30000.0
mersedes        NaN
onix        40000.0
spark       12000.0
tracker     44000.0
dtype: float64

In [ ]:
cars_series.name = 'chirchiq avtosalon' # bu yerda seriesga nom berdik.

In [ ]:
cars_series.index.name = 'modellar' # bu yerda series indexlariga umumiy nom berdik.

In [ ]:
cars_series

modellar
spark       6000
cobalt     14000
gentra     15000
tracker    22000
onix       20000
Name: chirchiq avtosalon, dtype: int64

In [ ]:
cars_series.index.name

'modellar'

In [ ]:
cars_series.index # indexlar

Index(['spark', 'cobalt', 'gentra', 'tracker', 'onix'], dtype='object', name='modellar')

In [ ]:
cars_series.values # qiymatlar

array([ 6000, 14000, 15000, 22000, 20000])

In [ ]:
cars2_series.hasnans # nan qiymat bor bo'lsa true bo'lmasa false qaytaradi.

True

In [ ]:
cars_series.hasnans

False

In [ ]:
cars_series.dtype

dtype('int64')

In [ ]:
cars_series['onix'] = 'mavjud emas'

/tmp/ipykernel_6242/4094028953.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'mavjud emas' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  cars_series['onix'] = 'mavjud emas'

In [ ]:
cars_series

modellar
spark             6000
cobalt           14000
gentra           15000
tracker          22000
onix       mavjud emas
Name: chirchiq avtosalon, dtype: object

In [ ]:
cars_series.dtype

dtype('O')

In [ ]:
cars_series.is_unique # qiymatlar takrorlanmas ekanligini tekshiradi.

True

In [ ]:
cars_series.shape # series shaklini aniqlaydi.

(5,)

In [ ]:
cars_series.size # series hajmini aniqlaydi.

5

In [ ]:
cars_series

modellar
spark             6000
cobalt           14000
gentra           15000
tracker          22000
onix       mavjud emas
Name: chirchiq avtosalon, dtype: object

In [ ]:
cars_series.iloc[2] # elementlarga index tartib raqami bo'yicha murojat qiladi.

15000

In [ ]:
cars_series.iloc[0]

6000

In [ ]:
cars_series.iloc[-2:]

modellar
tracker          22000
onix       mavjud emas
Name: chirchiq avtosalon, dtype: object

In [ ]:
cars_series['gentra']

15000

In [ ]:
cars2_series

cobalt      14000.0
onix        20000.0
BMW             NaN
tracker     22000.0
spark        6000.0
gentra      15000.0
mersedes        NaN
dtype: float64

In [ ]:
cars2_series.max() # maximum qiymat qaytaradi.

22000.0

In [ ]:
cars2_series.min()

6000.0

In [ ]:
cars2_series.mean() # o'rta arifmetik qiymatini aniqlaydi.

np.float64(15400.0)

In [ ]:
namuna = Series()

In [ ]:
namuna

Series([], dtype: object)

In [ ]:
del namuna # to'liq o'chirib tashlash.

In [ ]:
cars_series.drop('onix') # elementlarni o'chirish uchun drop dan foydalanib o'chirib tashladik.

In [ ]:
cars_series = cars_series.astype(float) # malumot turini o'zgartirdik.

In [ ]:
cars_series.dtype

dtype('float64')

In [ ]:
cars_series

modellar
spark       6000.0
cobalt     14000.0
gentra     15000.0
tracker    22000.0
Name: chirchiq avtosalon, dtype: float64

In [ ]:
cars_series = cars_series[cars_series>=15000] # qiymati 15000 dan kichik bo'lgan barcha elementlarni o'chirib tashladik.

In [ ]:
cars_series

modellar
gentra     15000.0
tracker    22000.0
Name: chirchiq avtosalon, dtype: float64