<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/pandas/pandas_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ma'lumotlar tahlili. Pandas kutubxonasi.

## Foydali funksiyalar.

### Arifmetik amallar.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
ser1 = pd.Series([7.3, -3.5, 2.4, 1.4], index=['a', 'c', 'd', 'e'])
ser2 = pd.Series([-2.6, 4.6, -1.5, 4.2, 3.3], index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
ser1

a    7.3
c   -3.5
d    2.4
e    1.4
dtype: float64

In [ ]:
ser2

a   -2.6
c    4.6
e   -1.5
f    4.2
g    3.3
dtype: float64

In [ ]:
ser1+ser2 # 2 ta seriesni bir biriga qo'shganimizda mos elementlar bir biriga qo'shildi.

a    4.7
c    1.1
d    NaN
e   -0.1
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'), index=['Olma','Anor','Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('abc'), index=['Olma','Anor','Qovun','Anjir'])

In [ ]:
df1

        b    c    d
Olma  0.0  1.0  2.0
Anor  3.0  4.0  5.0
Uzum  6.0  7.0  8.0

In [ ]:
df2

         a     b     c
Olma   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Qovun  6.0   7.0   8.0
Anjir  9.0  10.0  11.0

In [ ]:
df1+df2 # bu yerda ham xuddi serieslardagidek qo'shish amali bajarildi. mos elementlar bir biriga qo'shildi va qolgan joylar nan qiymatini oldi.

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [ ]:
df1.add(df2, fill_value=0) # add methodidan foydalanib ikki dataframeni bir biniga qo'shdik va mavjud bo'lmagan elementlarini o bilan to'ldirdik.
                           # faqat ikkalasida ham mavjud bo'lmagan joylarni nan bilan to'ldirdik.

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [ ]:
df2- df1

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  1.0  1.0 NaN
Olma  NaN  1.0  1.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [ ]:
df2.sub(df1, fill_value=0) # ikki dataframelarni bir biridan ayirdik.

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [ ]:
df2.rsub(df1, fill_value=0)

         a     b     c    d
Anjir -9.0 -10.0 -11.0  NaN
Anor  -3.0  -1.0  -1.0  5.0
Olma   0.0  -1.0  -1.0  2.0
Qovun -6.0  -7.0  -8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [ ]:
df2.div(df1) # bo'lish methodini ishlatdik.

        a         b     c   d
Anjir NaN       NaN   NaN NaN
Anor  NaN  1.333333  1.25 NaN
Olma  NaN       inf  2.00 NaN
Qovun NaN       NaN   NaN NaN
Uzum  NaN       NaN   NaN NaN

In [ ]:
df2.floordiv(df1, fill_value=1) # bo'ldik va butun qismini oldik.

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0  0.0
Olma   0.0   inf   2.0  0.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   0.0   0.0  0.0

In [ ]:
df2.mul(df1, fill_value=1) # ko'paytirish methodini ishlatdik.

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0  12.0  20.0  5.0
Olma   0.0   0.0   2.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [ ]:
df2.pow(2) # darajaga oshirdik.

          a      b      c
Olma    0.0    1.0    4.0
Anor    9.0   16.0   25.0
Qovun  36.0   49.0   64.0
Anjir  81.0  100.0  121.0

### Obyektning elementlariga funksiyalarni qo'llash.

In [ ]:
df3 = pd.DataFrame(np.random.randn(3,4), index=['a','b','c'], columns=['Olma','Anor','Uzum','Qovun'])
df3

       Olma      Anor      Uzum     Qovun
a -1.108994 -0.128031  0.497181 -0.059388
b -1.491865  0.971162 -0.341307 -0.282474
c -0.476741  0.767705 -0.719712 -0.535460

In [ ]:
np.abs(df3) # barcha elementlarning ishoralarini + ga o'zgartirdik.

       Olma      Anor      Uzum     Qovun
a  1.108994  0.128031  0.497181  0.059388
b  1.491865  0.971162  0.341307  0.282474
c  0.476741  0.767705  0.719712  0.535460

In [ ]:
np.round(df3) # barcha elementlarni yaxlitladik.

   Olma  Anor  Uzum  Qovun
a  -1.0  -0.0   0.0   -0.0
b  -1.0   1.0  -0.0   -0.0
c  -0.0   1.0  -1.0   -1.0

In [ ]:
df3.apply(np.abs)

       Olma      Anor      Uzum     Qovun
a  1.108994  0.128031  0.497181  0.059388
b  1.491865  0.971162  0.341307  0.282474
c  0.476741  0.767705  0.719712  0.535460

In [ ]:
df3.apply(sum, axis=1)

a   -0.799233
b   -1.144485
c   -0.964207
dtype: float64

In [ ]:
l = lambda x:x.max()-x.min()

In [ ]:
df3.apply(l)

Olma     1.015125
Anor     1.099193
Uzum     1.216892
Qovun    0.476071
dtype: float64

In [ ]:
def make_ser(a):
  return pd.Series([a.max(), a.min()], index=['max', 'min'])

In [ ]:
df3.apply(make_ser)

         Olma      Anor      Uzum     Qovun
max -0.476741  0.971162  0.497181 -0.059388
min -1.491865 -0.128031 -0.719712 -0.535460

In [ ]:
df3.applymap(lambda x:x**3) # bu yerda har bir element uchun funksiyani qo'lladik.

/tmp/ipykernel_2776/3179586259.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df3.applymap(lambda x:x**3)

       Olma      Anor      Uzum     Qovun
a -1.363917 -0.002099  0.122897 -0.000209
b -3.320389  0.915957 -0.039759 -0.022539
c -0.108355  0.452463 -0.372800 -0.153525

## reytinglash(ranking) va tartiblash(sorting)

In [ ]:
ser5 = pd.Series([2,4,1,9,7], index=["c",'b','a','e','d'])
ser5

c    2
b    4
a    1
e    9
d    7
dtype: int64

In [ ]:
ser5.sort_index() # series abyektimizni indexlari bo'yicha tartibladik.

a    1
b    4
c    2
d    7
e    9
dtype: int64

In [ ]:
ser5.sort_values() # series abyektimizni qiymatlari bo'yicha tartibladik

a    1
c    2
b    4
d    7
e    9
dtype: int64

In [2]:
df5 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv",index_col=0) # internetdan dataframe yuklab oldik.
df5.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
df5.shape

(2499, 12)

In [ ]:
df5.sort_index()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [ ]:
df5.sort_index(axis=1) # dataframeni qatorlar bo'yicha tartibladik.

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df5.sort_index(ascending=False) # teskari tartibda tartibladik.

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
...,...,...,...,...,...,...,...,...,...,...,...,...
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left

In [ ]:
df5.sort_values(by='price').head(20)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
530,0,chevrolet,door,2003,salvage insurance,194673,gray,1gndt13s632267445,167650636,texas,usa,17 hours left
522,0,ford,door,2008,salvage insurance,145483,red,1fmcu03128kc80487,167357813,oklahoma,usa,17 hours left
516,0,peterbilt,truck,2009,salvage insurance,982486,blue,1xp7d49x09d784257,167529788,florida,usa,17 hours left
514,0,lincoln,door,2005,salvage insurance,89705,green,1lnhm87a25y619997,167154617,minnesota,usa,17 hours left
351,0,chevrolet,door,2008,salvage insurance,159266,gray,2g1wb58kx81220813,167650796,california,usa,19 hours left
354,0,ford,pickup,2009,salvage insurance,180364,blue,1ftyr10d19pa60391,167360535,tennessee,usa,2 days left
144,0,dodge,door,2014,salvage insurance,123660,silver,1c3cdzab0en111068,167756167,utah,usa,2 days left
141,0,dodge,van,2008,salvage insurance,177948,orange,2d8hn44h88r669549,167756157,utah,usa,2 days left
313,0,ford,van,1998,salvage insurance,186855,blue,2fmda5143wba16791,167359170,california,usa,19 hours left
314,0,ford,door,2013,salvage insurance,94004,black,3fa6p0h74dr270819,167610728,minnesota,usa,17 hours left
318,0,chevrolet,door,2009,salvage insurance,117059,black,kl1td66e39b645208,167418694,colorado,usa,18 hours left
305,0,ford,door,2003,salvage insurance,246065,gold,1fafp55u03a242094,167610324,kansas,usa,8 days left
297,0,honda,door,2003,salvage insurance,152608,white,1hgcm56363a030975,167552893,arkansas,usa,17 hours left
310,0,chevrolet,door,2003,salvage insurance,194673,gray,1gndt13s632267445,167650636,texas,usa,18 hours left
309,0,chevrolet,door,2004,salvage insurance,0,maroon,3gnek12t74g240524,167418651,wyoming,usa,18 hours left
355,0,ford,door,2009,salvage insurance,184889,black,1fahp35n09w109143,167611047,illinois,usa,17 hours left
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left
443,0,chevrolet,coupe,2008,salvage insurance,270080,yellow,1g1al18f187245041,167650422,illinois,usa,17 hours left
196,0,ford,mpv,2017,clean vehicle,76858,white,1fbax2cv0hkb32599,167656523,texas,usa,2 days left
371,0,ford,door,1998,salvage insurance,131367,white,1ftrf18l7wka62471,167611301,illinois,usa,17 hours left

In [ ]:
df5.sort_values(by=['price','year'], ascending=False).head(20)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left
1331,65200,ford,max,2019,clean vehicle,18138,white,1fmjk2at0kea08300,167737619,kentucky,usa,21 hours left
667,63200,chevrolet,corvette,2016,clean vehicle,4266,red,1g1ys2d6xg5609979,167783470,california,usa,2 days left
1334,63000,ford,srw,2019,clean vehicle,11640,no_color,1ft7w2bt7ked44785,167780677,illinois,usa,21 hours left
1343,63000,ford,srw,2018,clean vehicle,17942,black,1ft7w2bt3jec31754,167780684,illinois,usa,21 hours left
645,62000,chevrolet,corvette,2016,clean vehicle,19403,white,1g1yt2d6xg5612796,167780136,illinois,usa,21 hours left
399,61200,bmw,series,2020,clean vehicle,7509,black,wba7t2c04lgl17687,167417053,california,usa,7 days left
1341,60200,ford,srw,2019,clean vehicle,31744,white,1ft7w2bt6ked11132,167738659,kentucky,usa,21 hours left
1342,60000,ford,srw,2018,clean vehicle,18062,black,1ft7w2btxjeb54932,167780683,illinois,usa,2 days left
1896,59975,ford,f-150,2019,clean vehicle,71,white,1ftfw1rg5kfa62833,167801448,florida,usa,Listing Expired
1901,59975,ford,f-150,2019,clean vehicle,174,black,1ftfw1rg6kfc08396,167801451,florida,usa,Listing Expired
2088,59900,ford,max,2020,clean vehicle,2162,no_color,1fmjk2at4lea11492,167762991,ohio,usa,21 hours left
414,58500,ford,srw,2019,clean vehicle,21527,blue,1ft8w3bt3kee15023,167765561,washington,usa,21 hours left
1368,58500,ford,expedition,2019,clean vehicle,4970,gray,1fmju2at7kea02696,167781639,california,usa,21 hours left
1339,57700,ford,srw,2019,clean vehicle,21101,red,1ft7w2bt6kee59894,167738658,kentucky,usa,21 hours left
1327,56700,ford,f-150,2019,clean vehicle,13884,white,1ftew1eg0kfa74454,167737612,kentucky,usa,21 hours left

In [ ]:
df5['rating']=df5['mileage'].rank(method='average') # mashinalarni yurgan kilometri bo'yicha reytingladik.
df5.sort_values('rating')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
1236,4200,ford,door,2013,clean vehicle,0,no_color,1fadp3j23dl155179,167773673,pennsylvania,usa,2 days left,3.5
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,3.5
309,0,chevrolet,door,2004,salvage insurance,0,maroon,3gnek12t74g240524,167418651,wyoming,usa,18 hours left,3.5
1619,650,ford,door,2017,salvage insurance,0,black,1fadp3k21hl268441,167651911,california,usa,2 days left,3.5
504,100,peterbilt,truck,2012,salvage insurance,0,blue,1xp4d49x1cd144875,167529787,florida,usa,17 hours left,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,2000,chevrolet,pickup,2003,clean vehicle,507985,red,1gcgc24u53z128586,167781223,wisconsin,usa,21 hours left,2495.0
490,475,peterbilt,truck,2012,salvage insurance,902041,gold,1xp4d49x9cd123630,167529786,florida,usa,17 hours left,2496.0
516,0,peterbilt,truck,2009,salvage insurance,982486,blue,1xp7d49x09d784257,167529788,florida,usa,17 hours left,2497.0
1827,3200,ford,door,2013,clean vehicle,999999,silver,1fadp3k21dl266148,167727773,south carolina,usa,21 hours left,2498.0
528,1025,peterbilt,truck,2010,salvage insurance,1017936,color:,1xp7d49x0ad793710,167529842,georgia,usa,17 hours left,2499.0

In [ ]:
df5.info() # dataframe haqida qisqacha malumot.

<class 'pandas.core.frame.DataFrame'>
Index: 2499 entries, 0 to 2498
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         2499 non-null   int64
 1   brand         2499 non-null   object
 2   model         2499 non-null   object
 3   year          2499 non-null   int64
 4   title_status  2499 non-null   object
 5   mileage       2499 non-null   int64
 6   color         2499 non-null   object
 7   vin           2499 non-null   object
 8   lot           2499 non-null   int64
 9   state         2499 non-null   object
 10  country       2499 non-null   object
 11  condition     2499 non-null   object
 12  rating        2499 non-null   float64
dtypes: float64(1), int64(4), object(8)
memory usage: 273.3+ KB

In [ ]:
df5.describe()

              price         year       mileage           lot       rating
count   2499.000000  2499.000000  2.499000e+03  2.499000e+03  2499.000000
mean   18767.671469  2016.714286  5.229869e+04  1.676914e+08  1250.000000
std    12116.094936     3.442656  5.970552e+04  2.038772e+05   721.543443
min        0.000000  1973.000000  0.000000e+00  1.593488e+08     3.500000
25%    10200.000000  2016.000000  2.146650e+04  1.676253e+08   625.500000
50%    16900.000000  2018.000000  3.536500e+04  1.677451e+08  1250.000000
75%    25555.500000  2019.000000  6.347250e+04  1.677798e+08  1874.500000
max    84900.000000  2020.000000  1.017936e+06  1.678055e+08  2499.000000

### Korrellatsiya

In [ ]:
df5['price'].corr(df5['year']) # price va year ustunlarining bir-biri bilan bog'liqligini aniqladik.

np.float64(0.418273568491795)

In [ ]:
df5.corr(numeric_only=True) # barcha number qatorlarni solishtirdik.

            price      year   mileage       lot
price    1.000000  0.418274 -0.400838  0.159369
year     0.418274  1.000000 -0.594686  0.164582
mileage -0.400838 -0.594686  1.000000 -0.130475
lot      0.159369  0.164582 -0.130475  1.000000

In [ ]:
df5.corrwith(df5['year'],numeric_only=True) # bitta ustunni qolganlari bilan solishtirdik.

price      0.418274
year       1.000000
mileage   -0.594686
lot        0.164582
dtype: float64

### Filtrlash

In [ ]:
df5['state'].unique() # mavjud shtatlarni chiqardik.

array(['new jersey', 'tennessee', 'georgia', 'virginia', 'florida',
       'texas', 'california', 'north carolina', 'ohio', 'new york',
       'pennsylvania', 'south carolina', 'michigan', 'washington',
       'arizona', 'utah', 'kentucky', 'massachusetts', 'nebraska',
       'ontario', 'missouri', 'minnesota', 'oklahoma', 'connecticut',
       'indiana', 'arkansas', 'kansas', 'wyoming', 'colorado', 'illinois',
       'wisconsin', 'mississippi', 'maryland', 'oregon', 'west virginia',
       'nevada', 'rhode island', 'louisiana', 'alabama', 'new mexico',
       'idaho', 'new hampshire', 'montana', 'vermont'], dtype=object)

In [ ]:
len(df5['state'].unique()) # shtatlarning sonini chiqardik.

44

In [ ]:
df5['state'].value_counts() # har bir shtatda nechtadan mashina tegishli ekanini aniqladik.

state
pennsylvania      299
florida           246
texas             214
california        190
michigan          169
north carolina    146
minnesota         119
illinois          113
wisconsin          94
virginia           90
new jersey         87
nevada             85
oklahoma           71
south carolina     64
new york           58
georgia            51
missouri           46
arizona            33
ohio               31
oregon             27
massachusetts      27
tennessee          26
connecticut        25
mississippi        24
colorado           21
west virginia      21
alabama            17
washington         14
indiana            14
arkansas           12
louisiana          11
utah               10
kentucky            9
ontario             7
nebraska            4
kansas              4
new mexico          4
maryland            4
new hampshire       4
rhode island        2
vermont             2
idaho               2
wyoming             1
montana             1
Name: count, dtype: int64

In [3]:
df5['brand'].unique()

array(['toyota', 'ford', 'dodge', 'chevrolet', 'gmc', 'chrysler', 'kia',
       'buick', 'infiniti', 'mercedes-benz', 'jeep', 'bmw', 'cadillac',
       'hyundai', 'mazda', 'honda', 'heartland', 'jaguar', 'acura',
       'harley-davidson', 'audi', 'lincoln', 'lexus', 'nissan', 'land',
       'maserati', 'peterbilt', 'ram'], dtype=object)

In [21]:
df5[(df5['year']>2018) & (df5['price']<20000) & (df5['brand']=='jeep')] # malumotlarni filtrladik.

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
46,16200,jeep,compass,2019,clean vehicle,30061,red,3c4njccb3kt676336,167802530,north carolina,usa,2 days left
51,16000,jeep,compass,2019,clean vehicle,31594,silver,3c4njccb0kt676343,167802531,north carolina,usa,2 days left
71,15800,jeep,compass,2019,clean vehicle,35595,charcoal,3c4njccb4kt662767,167802541,north carolina,usa,2 days left
76,15900,jeep,compass,2019,clean vehicle,34502,red,3c4njccb7kt660088,167802543,north carolina,usa,2 days left
81,17900,jeep,compass,2019,clean vehicle,32501,red,3c4njddb7kt682015,167802544,north carolina,usa,2 days left
86,18000,jeep,compass,2019,clean vehicle,29245,gray,3c4njddb0kt686052,167802545,north carolina,usa,2 days left
289,6530,jeep,mpv,2019,clean vehicle,10185,black,3c4njdcb3kt659526,167680488,georgia,usa,17 hours left
298,4400,jeep,mpv,2019,clean vehicle,17911,green,3c4njcbbxkt664931,167680540,georgia,usa,17 hours left
307,10900,jeep,mpv,2019,clean vehicle,13273,red,1c4hjxeg1kw609998,167264249,michigan,usa,2 days left
316,10900,jeep,mpv,2019,clean vehicle,14195,orange,1c4hjxeg1kw608401,167264250,michigan,usa,2 days left
317,6330,jeep,mpv,2019,clean vehicle,43965,red,1c4pjldbxkd300679,167698671,florida,usa,22 hours left
358,6930,jeep,mpv,2019,clean vehicle,47798,red,1c4pjmdx4kd197521,167698679,florida,usa,22 hours left
365,11380,jeep,mpv,2019,clean vehicle,12038,black,1c4hjxeg2kw600727,167271446,michigan,usa,2 days left
461,5800,jeep,mpv,2019,clean vehicle,30546,silver,1c4pjldb3kd419559,167697949,ohio,usa,2 days left
473,11000,jeep,mpv,2019,clean vehicle,8930,red,1c4hjxeg0kw596497,167256941,michigan,usa,2 days left
474,4950,jeep,mpv,2019,clean vehicle,46985,silver,1c4pjllb6kd184477,167697950,ohio,usa,2 days left
485,11200,jeep,mpv,2019,clean vehicle,8395,yellow,1c4hjxeg7kw589272,167256942,michigan,usa,2 days left
499,11200,jeep,mpv,2019,clean vehicle,12905,gray,1c4hjxeg7kw590115,167256952,michigan,usa,2 days left
500,8610,jeep,mpv,2019,clean vehicle,22123,silver,1c4rjebg1kc776053,167697952,ohio,usa,2 days left
512,11100,jeep,mpv,2019,clean vehicle,11229,white,1c4hjxegxkw589301,167256954,michigan,usa,2 days left
524,10910,jeep,mpv,2019,clean vehicle,12253,red,1c4hjxeg8kw651309,167256956,michigan,usa,2 days left
536,11100,jeep,mpv,2019,clean vehicle,11449,yellow,1c4hjxegxkw600703,167256957,michigan,usa,2 days left
548,11030,jeep,mpv,2019,clean vehicle,10861,yellow,1c4hjxeg5kw608448,167256958,michigan,usa,2 days left

In [16]:
filtr = df5.brand.isin(['ford']) # filtrlashning yana bir usuli.
len(filtr)

2499

In [17]:
df5[filtr]

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
9,5250,ford,mpv,2017,clean vehicle,63418,black,2fmpk3j92hbc12542,167656121,texas,usa,2 days left
14,20700,ford,door,2013,clean vehicle,100757,black,1ftfw1et7dfa47790,167753916,virginia,usa,22 hours left
18,5210,ford,mpv,2017,clean vehicle,35714,white,2fmpk3j95hbb73607,167656124,texas,usa,2 days left
...,...,...,...,...,...,...,...,...,...,...,...,...
2199,13800,ford,fusion,2019,clean vehicle,29345,white,3fa6p0lu1kr222799,167802379,north carolina,usa,2 days left
2200,56000,ford,srw,2018,clean vehicle,25371,black,1ft7w2bt4jec50359,167749689,pennsylvania,usa,3 days left
2201,13800,ford,fusion,2019,clean vehicle,30054,silver,3fa6p0lu3kr210749,167802380,north carolina,usa,2 days left
2202,45800,ford,srw,2018,clean vehicle,11173,white,1ft7w2bt3jeb02932,167749690,pennsylvania,usa,2 days left
2203,13800,ford,fusion,2019,clean vehicle,30902,no_color,3fa6p0lu8kr225585,167802381,north carolina,usa,2 days left