<a href="https://colab.research.google.com/github/farxod0518/data_science_and_AI_learning/blob/main/pandas/pandas_1_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Pandas kutubxonasi.

# **AMALIYOT**
## 3.1 Series va Index

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [3]:
# Javobni shuyerga yozing
import pandas as pd
import numpy as np

In [1]:
#@title To'g'ri javob
import pandas as pd
import numpy as np

### **2-mashq.** O'zbekiston Respublikasi viloyatlaridan iborat bir o'lchamli Series obyektini yarating

In [7]:
# Javobni shu yerga yozing
ser = pd.Series(['andijon','buxoro',"farg'ona","jizzax","xorazm","namangan","navoiy","qashqadaryo","qoraqalpog'iston","samarqand","sirdaryo","surxondaryo","toshkent"])
ser

0              andijon
1               buxoro
2             farg'ona
3               jizzax
4               xorazm
5             namangan
6               navoiy
7          qashqadaryo
8     qoraqalpog'iston
9            samarqand
10            sirdaryo
11         surxondaryo
12            toshkent
dtype: object

In [ ]:
#@title **To'g'ri javob**
obj = pd.Series(
    [
        "Andijon",
        "Buxoro",
        "Farg'ona",
        "Jizzax",
        "Xorazm",
        "Namangan",
        "Navoiy",
        "Qashqadaryo",
        "Qoraqalpog'iston Respublikasi",
        "Samarqand",
        "Sirdaryo",
        "Surxondaryo",
        "Toshkent",
    ]
)
print(obj)

0                           Andijon
1                            Buxoro
2                          Farg'ona
3                            Jizzax
4                            Xorazm
5                          Namangan
6                            Navoiy
7                       Qashqadaryo
8     Qoraqalpog'iston Respublikasi
9                         Samarqand
10                         Sirdaryo
11                      Surxondaryo
12                         Toshkent
dtype: object

### **3-mashq.** Yuqorida yaratilgan Series obyektining barcha qiymaltarini chiqaring

In [11]:
# Javobni shuyerga yozing
ser.values

array(['andijon', 'buxoro', "farg'ona", 'jizzax', 'xorazm', 'namangan',
       'navoiy', 'qashqadaryo', "qoraqalpog'iston", 'samarqand',
       'sirdaryo', 'surxondaryo', 'toshkent'], dtype=object)

In [ ]:
# @title **To'g'ri javob**
obj.values

array(['Andijon', 'Buxoro', "Farg'ona", 'Jizzax', 'Xorazm', 'Namangan',
       'Navoiy', 'Qashqadaryo', "Qoraqalpog'iston Respublikasi",
       'Samarqand', 'Sirdaryo', 'Surxondaryo', 'Toshkent'], dtype=object)

### **4-mashq.** Yuqoridagi Series obyektining eng birinchi qiymatini chiqaring

In [12]:
# Javobni shuyerga yozing
ser.values[0]

'andijon'

In [ ]:
# @title **To'g'ri javob**
obj[0]

'Andijon'

### **5-mashq.** Yuqoridagi Series obyektining eng oxirgi qiymatini chiqaring

In [13]:
# Javobni shuyerga yozing
ser.values[-1]

'toshkent'

In [ ]:
# @title **To'g'ri javob**
obj[12]

'Toshkent'

### **6-mashq.** Yuqoridagi Series obyekti uzunligini chiqaring

In [16]:
# Javobni shuyerga yozing
len(ser.values)

13

In [ ]:
# @title **To'g'ri javob**
obj.size

13

### **7-mashq.** Yuqoridagi Series obyektining o'rtasidan 3 ta qiymat chiqaring

In [21]:
# Javobni shuyerga yozing
ser[[5,6,7]]

5       namangan
6         navoiy
7    qashqadaryo
dtype: object

In [ ]:
# @title **To'g'ri javob**

obj[[5, 6, 7]]

5       Namangan
6         Navoiy
7    Qashqadaryo
dtype: object

### **8-mashq.** Quyidagi Series obyektini yarating.
**Ahamiyat bering. `Series` obyekti indeksi sifatida viloyatlar nomi ishlatilgan**

In [28]:
# @title
ind = obj.values
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
obj2 = pd.Series(aholi, index=ind)
print(obj2)

NameError: name 'obj' is not defined

In [48]:
# Javobni shuyerga yozing
ser2 = pd.Series([1899000,1384700,2597000,910500,1200000,1862000,767500,2029000,1200000,2322000,648100,1676000,4450000],index=['andijon','buxoro',"farg'ona","jizzax","xorazm","namangan","navoiy","qashqadaryo","qoraqalpog'iston respublikasi","samarqand","sirdaryo","surxondaryo","toshkent"])
ser2

andijon                          1899000
buxoro                           1384700
farg'ona                         2597000
jizzax                            910500
xorazm                           1200000
namangan                         1862000
navoiy                            767500
qashqadaryo                      2029000
qoraqalpog'iston respublikasi    1200000
samarqand                        2322000
sirdaryo                          648100
surxondaryo                      1676000
toshkent                         4450000
dtype: int64

### **9-mashq.** Yuqoridagi `Series` obyektidan Jizzax, Buxoro va Namangan viloyatlarining aholisini chiqaring

In [26]:
# Javobni shuyerga yozing
print(ser2[['jizzax','buxoro','namangan']])

jizzax       910500
buxoro      1384700
namangan    1862000
dtype: int64

In [27]:
# @title **To'g'ri javob**
obj2[["Jizzax", "Buxoro", "Namangan"]]

NameError: name 'obj2' is not defined

### **10-mashq.** Yuqoridagi `Series` obyektidan aholi soni 1 milliondan kam va ko'p bo'lgan viloyatlarni alohida chiqaring

In [30]:
# Javobni shuyerga yozing
print("aholisi 1 milliondan ko'p bo'lgan viloyatlar")
print(ser2[ser2>1000000])
print("aholisi 1 milliondan kam bo'lgan viloyatlar")
print(ser2[ser2<1000000])

aholisi 1 milliondan ko'p bo'lgan viloyatlar
andijon             1899000
buxoro              1384700
farg'ona            2597000
xorazm              1200000
namangan            1862000
qashqadaryo         2029000
qoraqalpog'iston    1200000
samarqand           2322000
surxondaryo         1676000
toshkent            4450000
dtype: int64
aholisi 1 milliondan kam bo'lgan viloyatlar
jizzax      910500
navoiy      767500
sirdaryo    648100
dtype: int64

In [ ]:
# @title **To'g'ri javob**
print("Aholisi 1 milliondan ko'p viloyatlar")
print(obj2[obj2 > 1_000_000])
# Pythonda katta sonlarni yozishda 0 orasini _ bilan ajratish mumkin

Aholisi 1 milliondan ko'p viloyatlar
Andijon                          1899000
Buxoro                           1384700
Farg'ona                         2597000
Xorazm                           1200000
Namangan                         1862000
Qashqadaryo                      2029000
Qoraqalpog'iston Respublikasi    1200000
Samarqand                        2322000
Surxondaryo                      1676000
Toshkent                         4450000
dtype: int64

In [ ]:
# @title
print("Aholisi 1 milliondan kam viloyatlar")
print(obj2[obj2 < 1_000_000])

Aholisi 1 milliondan kam viloyatlar
Jizzax      910500
Navoiy      767500
Sirdaryo    648100
dtype: int64

### **11-mashq.** Aholisi 1 milliondan ko'p davlatlar orasida Navoiy viloyati bor/yo'qligini tekshiring

In [35]:
# Javobni shuyerga yozing
'navoiy' in ser2[ser2>1000000]

False

In [ ]:
# @title **To'g'ri javob**
"Navoiy" in obj2[obj2 > 1_000_000]

False

### **12-mashq.** Quyidagi lug'atda viloyatlar va ularning maydonlari berilgan. Lug'atdan yangi `Series` obyektini yarating va unga "Hududlar hajmi" deb nom bering

In [36]:
dict = {
    "Andijon": 4200,
    "Buxoro": 39400,
    "Farg'ona": 6800,
    "Jizzax": 20500,
    "Xorazm": 6300,
    "Namangan": 7900,
    "Navoiy": 110800,
    "Qashqadaryo": 28400,
    "Qoraqalpog'iston Respublikasi": 160000,
    "Samarqand": 16400,
    "Sirdaryo": 5100,
    "Surxondaryo": 20800,
    "Toshkent": 15300,
}

In [39]:
# Javobni shuyerga yozing
ser3 = pd.Series(dict)
ser3.name = "hududlar hajmi"
print(ser3)

Andijon                            4200
Buxoro                            39400
Farg'ona                           6800
Jizzax                            20500
Xorazm                             6300
Namangan                           7900
Navoiy                           110800
Qashqadaryo                       28400
Qoraqalpog'iston Respublikasi    160000
Samarqand                         16400
Sirdaryo                           5100
Surxondaryo                       20800
Toshkent                          15300
Name: hududlar hajmi, dtype: int64

In [ ]:
#@title To'g'ri javob
obj3 = pd.Series(dict)
obj3.name = "Hudular hajmi"
print(obj3)

Andijon                            4200
Buxoro                            39400
Farg'ona                           6800
Jizzax                            20500
Xorazm                             6300
Namangan                           7900
Navoiy                           110800
Qashqadaryo                       28400
Qoraqalpog'iston Respublikasi    160000
Samarqand                         16400
Sirdaryo                           5100
Surxondaryo                       20800
Toshkent                          15300
Name: Hudular hajmi, dtype: int64

### **13-mashq.** Yuqoridagi `Series` obyektidan hududi eng katta va eng kichik elementlarni chiqaring

In [46]:
# Javobni shuyerga yozing
print(f"eng katta hudud: {ser3.idxmax()}")
print(f"eng kichik hudud: {ser3.idxmin()}")

eng katta hudud: Qoraqalpog'iston Respublikasi
eng kichik hudud: Andijon

In [ ]:
#@title To'g'ri javob
print(f"Eng katta hudud: {obj3.idxmax()}")
print(f"Eng kichik hudud: {obj3.idxmin()}")

Eng katta hudud: Qoraqalpog'iston Respublikasi
Eng kichik hudud: Andijon

### **14-mashq.** Yuqoridagi eng katta va eng kichik hududlar aholisi sonini chiqaring

In [51]:
# Javobni shuyerga yozing
print(f"{ser3.idxmax()} aholisi: {ser2[ser3.idxmax().lower()]}")
print(f"{ser3.idxmin()} aholisi: {ser2[ser3.idxmin().lower()]}")

Qoraqalpog'iston Respublikasi aholisi: 1200000
Andijon aholisi: 1899000

In [ ]:
#@title To'g'ri javob
print(f"{obj3.idxmax()} aholisi {obj2[obj3.idxmax()]}")
print(f"{obj3.idxmin()} aholisi {obj2[obj3.idxmin()]}")

Qoraqalpog'iston Respublikasi aholisi 1200000
Andijon aholisi 1899000

### **15-mashq**. Yuqoridagi hudulardan O'zbekiston Respublikasi hududini hisoblang

In [56]:
# Javobni shuyerga yozing
sum(ser3)

441900

In [ ]:
#@title To'g'ri javob
sum(obj3)

441900

### **16-mashq.** Aholisi eng ko'p va eng kam hududlarning hajmini va aholi sonini chiqaring

In [59]:
# Javobni shuyerga yozing
print(f"{ser2.idxmax()} hududi {ser3[ser2.idxmax().title()]}kv.km, aholisi {ser2.max()}")
print(f"{ser2.idxmin()} hududi {ser3[ser2.idxmin().title()]}kv.km, aholisi {ser2.min()}")

toshkent hududi 15300kv.km, aholisi 4450000
sirdaryo hududi 5100kv.km, aholisi 648100

In [ ]:
#@title To'g'ri javob
print(f"{obj2.idxmax()} hududi {obj3[obj2.idxmax()]}kv.km, aholisi {obj2[obj2.idxmax()]}")
print(f"{obj2.idxmin()} hududi {obj3[obj2.idxmin()]}kv.km, aholisi {obj2[obj2.idxmin()]}")

Toshkent hududi 15300kv.km, aholisi 4450000
Sirdaryo hududi 5100kv.km, aholisi 648100

### **17-mashq.** Yuqoridagi ikki obyektdan foydalangan holda O'zbekiston respublikasi tarkibidagi hududlarni avval aholi soni bo'yicha, keyin esa hajmi bo'yicha tartiblab chiqaring

In [63]:
# Javobni shuyerga yozing
print("hududlar hajmi bo'yicha tartiblash")
print(ser3.sort_values())
print("aholi soni bo'yicha tartiblash")
print(ser2.sort_values())

hududlar hajmi bo'yicha tartiblash
Andijon                            4200
Sirdaryo                           5100
Xorazm                             6300
Farg'ona                           6800
Namangan                           7900
Toshkent                          15300
Samarqand                         16400
Jizzax                            20500
Surxondaryo                       20800
Qashqadaryo                       28400
Buxoro                            39400
Navoiy                           110800
Qoraqalpog'iston Respublikasi    160000
Name: hududlar hajmi, dtype: int64
aholi soni bo'yicha tartiblash
sirdaryo                          648100
navoiy                            767500
jizzax                            910500
xorazm                           1200000
qoraqalpog'iston respublikasi    1200000
buxoro                           1384700
surxondaryo                      1676000
namangan                         1862000
andijon                          1899000
qashqadaryo                      2029000
samarqand                        2322000
farg'ona                         2597000
toshkent                         4450000
dtype: int64

In [ ]:
#@title To'g'ri javob
print("Hududlar hajmi bo'yicha tartiblash")
obj3.sort_values()

Hududlar hajmi bo'yicha tartiblash

Andijon                            4200
Sirdaryo                           5100
Xorazm                             6300
Farg'ona                           6800
Namangan                           7900
Toshkent                          15300
Samarqand                         16400
Jizzax                            20500
Surxondaryo                       20800
Qashqadaryo                       28400
Buxoro                            39400
Navoiy                           110800
Qoraqalpog'iston Respublikasi    160000
Name: Hudular hajmi, dtype: int64

In [ ]:
#@title To'g'ri javob
print("Aholi soni bo'yicha tartiblash")
obj2.sort_values()

Aholi soni bo'yicha tartiblash

Sirdaryo                          648100
Navoiy                            767500
Jizzax                            910500
Xorazm                           1200000
Qoraqalpog'iston Respublikasi    1200000
Buxoro                           1384700
Surxondaryo                      1676000
Namangan                         1862000
Andijon                          1899000
Qashqadaryo                      2029000
Samarqand                        2322000
Farg'ona                         2597000
Toshkent                         4450000
dtype: int64